### ISSUE TITLE
ジョーカーのあとスペードの３が出たら自動的に全員パスする

### ISSUE THREAD

**Issue by guredora403** [yncat/dfg#11]
全員パスする以外選択肢がないです。

**Comment by yamahubuki** [comment]
合わせて、全てのスペ3ができった後のジョーカーと、ジョーカーができったあとの２くらいまでは対応して頂けると。

**Comment by yamahubuki** [comment]
自動パスじゃなくて8切りと同じように場のカードを流すのがよさそう。ログも見やすい。

まずは、何があってもあり得ないもの＝スペ3返しとその時一番強いカードを含む階段で実装お願いします。

**Comment by yncat** [comment]
https://github.com/yncat/dfg-simulator/commit/17c4f9219e2563d2c9d3f86c52cf5bc16034f5f5 で実装しました。
