### ISSUE TITLE
スペ3返しでないスペ3は禁止あがりから除外する

### ISSUE THREAD

**Issue by yamahubuki** [yncat/dfg#20]
ただの3としてスペ3を使ったにもかかわらず禁止あがりとなってしまうらしいです。

これはあんまりなので治してあげてください。
マニュアルとも矛盾しています。

**Comment by yncat** [comment]
https://github.com/yncat/dfg-simulator/commit/f031d47c3c0837cc07dd0b8bcb4103425968f3d2 で修正しました。
