### ISSUE TITLE
プレイヤー名に空白のみが使用できてしまう

### ISSUE THREAD

**Issue by guredora403** [yncat/dfg#25]
完全に識別ができなくなってしまいます。

**Comment by yamahubuki** [comment]
合わせて、読点もプレイヤー名リストを画面表示する際の区切り文字なのでプレイヤー名としては使用禁止文字にしてほしいです。

**Comment by yncat** [comment]
https://github.com/yncat/dfg-server/commit/e2563d34f6ce50bf15d7d2e6d0ce2e03ac59a0ee で対応しました。デプロイ済み。
