### ISSUE TITLE
ゲーム開始時、一定の遅延を入れる

### ISSUE THREAD

**Issue by yamahubuki** [yncat/dfg#26]
次のゲームが始まる前に抜けたいと思っていた場合に、確実に抜けられるようにする。

ルームのオーナーがゲームを開始ボタンを押した後、手札が配られるまでに10秒程度の遅延を設け、ルーム内のプレイヤーに予告をする。

**Comment by yncat** [comment]
これは観戦/参加スイッチを入れることで対応するので一度閉じておきます
