### ISSUE TITLE
iOSで画面ロックされると退室してしまう

### ISSUE THREAD

**Issue by yama3nomori** [yncat/dfg#28]
プレイ/観戦問わず強制的に退室してしまいます。
ホームや別アプリに画面を切り替えても同様です。

AndroidではChrome/Firefoxで試してみていずれも退室にはなりませんでした。

**Comment by yncat** [comment]
これはiOSが画面非アクティブになったブラウザのwebsocketを切断するせいなので、セッションを持たせる(接続落ちしたプレイヤーを復帰できるようにする)対応を入れないと根本解決が厳しいです

**Comment by yncat** [comment]
@yama3nomori iPhoneでバックグラウンドになって接続が落ちても、5分以内に戻ってくれば再接続できる機能を付けました。操作手順は以下です。時間のあるときに試してみていただけると！

1. 普通にゲームに入る
2. ゲームを開始する
3. 別のアプリを起動したりして、ブラウザをバックグラウンドにする
4. 他の人のところに、「接続が切れました、5分以内に...」というメッセージが出るのを確認する
5. safariに戻ってくる
6. 「ロビー接続でエラーが発生しました」とか「ルーム接続でエラーが発生しました」とか出てくる
7. ページを再読み込みしろと言われるので再読み込みする
8. いつも名前を入れるはずのところに、再接続ボタンが現れるので押す
9. あら不思議、カムバック！

**Comment by yama3nomori** [comment]
これはありがたいです。ありがとうございます。
試してみましたが、
5.の操作によっては書かれている挙動と少し違うようです。
1.から4.までは問題ありません。


ケース1. ブックマークなどから大富豪に入り直した場合
記載通りに動作しています。

ケース2. アップスイッチャーやホーム画面のアイコンからサファリに戻った場合
7.まで進んだ後、ゲーム中の画面になります。
が、再接続はできていません。
スクラブで前の画面に戻ると8.の状態になり、再接続ができます。

**Comment by yncat** [comment]
今のところ再読み込みは手動でやる必要があります。ゲーム画面を終了するのはこれから入れる予定です。

**Comment by yncat** [comment]
再接続機能で問題が解決しているのでcloseします
