### ISSUE TITLE
スキップ有効時に5を出したときの挙動について

### ISSUE THREAD

**Issue by riku22** [yncat/dfg#37]
スキップを有効にした状態で、5を出しても出したカードが消えないようです。
また、5を出してあがると、ランク判定が行われず、あがることができません。
そのため、1度ルームを抜けたのですが、そうすると、未使用のカードとして出したはずの5が表示されています。

**Comment by yama3nomori** [comment]
上記の問題は修正できているようです。
ただ現在マルチスキップの場合__飛び石__でスキップしています。
プレイア A B C D
で
Aが5を2枚出した場合
Bスキップ
Cスルー
Dスキップ
で
Aに戻りました。
2枚目の5はCが出したように振る舞っています。

Dのターンになるのが正しいように認識しています。

**Comment by yncat** [comment]
@yama3nomori 今はこの仕様です。UNOのスキップってそうじゃなかったでしたっけ。最初は、2枚出したときはBとCを飛ばしてDになっていました。

**Comment by yncat** [comment]
ちなみに、スキップがぶっ壊れてたのを直したコミットはこれです
https://github.com/yncat/dfg-simulator/commit/01c4ac329f5566a139f1d30bdac2795b861bcb67

**Comment by yama3nomori** [comment]
こんな感じでいわれてますねー。
イメージしやすいのは前バージョンで、ゲーム性が高いのは現行かなと。
ただ後者はプレイアーが挙動をつかみにくいかなと思います。
[ウノでスキップカードを2枚出した場合、何人飛ばすんですか？自分... - Yahoo!知恵袋](https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1143461721)

**Comment by yncat** [comment]
イメージっていう意味でいうと、そうなんですよね。戻すかー

**Comment by yncat** [comment]
遅くなりましたが、
https://github.com/yncat/dfg-simulator/commit/c3724eb7a15d4fd47255a007c7d51d442993ad04
でマルチスキップの挙動を戻しました。
