### ISSUE TITLE
観戦中や上がった後、他プレイヤーの手札を見られるようにする

### ISSUE THREAD

**Issue by yamahubuki** [yncat/dfg#9]
一般的な大富豪ゲームに習って、暇つぶししやすいように、他のプレイヤーの手札を見て楽しめるようにしてほしいです。

**Comment by yamahubuki** [comment]
観戦中でこれができると、別ブラウザで不正ができてしまうのでダメぽ

**Comment by yncat** [comment]
これは今のところ実装予定がありません。
